default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: pomodorizer_development


test:
  <<: *default
  database: pomodorizer_test

production:
  <<: *default
  database: pomodorizer_production
  username: pomodorizer
  password: <%= ENV["POMODORIZER_DATABASE_PASSWORD"] %>
